curl -X PUT "localhost:9200/books/_doc/2" -H 'Content-Type: application/json' -d "{\"title\" : \"After Many a Summer Dies the Swan\"}"
curl -X PUT "localhost:9200/books/_doc/3" -H 'Content-Type: application/json' -d "{\"title\" : \"The Alien Corn (short story)\"}"
curl -X PUT "localhost:9200/books/_doc/4" -H 'Content-Type: application/json' -d "{\"title\" : \"All the King's Men\"}"
curl -X PUT "localhost:9200/books/_doc/5" -H 'Content-Type: application/json' -d "{\"title\" : \"As I Lay Dying\"}"
curl -X PUT "localhost:9200/books/_doc/6" -H 'Content-Type: application/json' -d "{\"title\" : \"Behold the Man\"}"
curl -X PUT "localhost:9200/books/_doc/7" -H 'Content-Type: application/json' -d "{\"title\" : \"A Time to Kill\"}"
curl -X PUT "localhost:9200/books/_doc/8" -H 'Content-Type: application/json' -d "{\"title\" : \"Blood's a Rover\"}"
curl -X PUT "localhost:9200/books/_doc/9" -H 'Content-Type: application/json' -d "{\"title\" : \"Cabbages and Kings\"}"
curl -X PUT "localhost:9200/books/_doc/10" -H 'Content-Type: application/json' -d "{\"title\" : \"Clouds of Witness\"}"
curl -X PUT "localhost:9200/books/_doc/11" -H 'Content-Type: application/json' -d "{\"title\" : \"The Curious Incident of the Dog in the Night-Time\"}"
curl -X PUT "localhost:9200/books/_doc/12" -H 'Content-Type: application/json' -d "{\"title\" : \"Death Be Not Proud\"}"
curl -X PUT "localhost:9200/books/_doc/13" -H 'Content-Type: application/json' -d "{\"title\" : \"Dying of the Light\"}"
curl -X PUT "localhost:9200/books/_doc/14" -H 'Content-Type: application/json' -d "{\"title\" : \"Endless Night\"}"
curl -X PUT "localhost:9200/books/_doc/15" -H 'Content-Type: application/json' -d "{\"title\" : \"Gone with the Wind\"}"
curl -X PUT "localhost:9200/books/_doc/16" -H 'Content-Type: application/json' -d "{\"title\" : \"How Sleep the Brave\"}"
curl -X PUT "localhost:9200/books/_doc/17" -H 'Content-Type: application/json' -d "{\"title\" : \"The Man Within\"}"
curl -X PUT "localhost:9200/books/_doc/18" -H 'Content-Type: application/json' -d "{\"title\" : \"The Moon by Night\"}"
curl -X PUT "localhost:9200/books/_doc/19" -H 'Content-Type: application/json' -d "{\"title\" : \"The Mirror Crack'd from Side to Side\"}"
curl -X PUT "localhost:9200/books/_doc/20" -H 'Content-Type: application/json' -d "{\"title\" : \"Of Human Bondage\"}"
