#!/usr/bin/env node
const fetch = require('node-fetch')
const CRS = require('fs').createReadStream
const path = require('path')

const fullUrl = url => `http://elasticsearch:9200/${url}?pretty`

const bulk = CRS(path.join('.', 'bulkPg.ldj'), {highWaterMark: 20 * 1024 * 1024})

fetch(fullUrl('books/book/_bulk'), {
  method: 'POST',
  body: bulk,
  headers: {
    'content-type': 'application/json'
  }
})
  .then(() => console.log('completed putting books'))
  .catch(console.error)
